# Generated by Django 4.2.6 on 2023-11-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecreds',
            name='app_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
