# Generated by Django 4.2.6 on 2023-11-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0002_googlecreds_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleusertokens',
            name='allow_digest',
            field=models.BooleanField(default=False),
        ),
    ]
