# Generated by Django 4.2.6 on 2023-10-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['title'], 'verbose_name_plural': 'Todo Items'},
        ),
    ]
