# Generated by Django 4.2.6 on 2023-10-24 20:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
