# Generated by Django 4.2.6 on 2023-11-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todoitem_content_alter_todoitem_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='added_to_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
