# Generated by Django 4.2.6 on 2023-11-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todoitem_added_to_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
