# Generated by Django 4.2.6 on 2023-11-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_googleuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleuser',
            name='ggogle_user_id',
        ),
        migrations.AddField(
            model_name='googleuser',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
