# Generated by Django 5.0.6 on 2024-07-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_msaltoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MSALToken',
        ),
    ]
