# Generated by Django 5.0.6 on 2024-07-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0009_outlookusertokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlookusertokens',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
